# Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

env = QT_QPA_PLATFORMTHEME,qt6ct

# ── CONFIGURACIÓN DE VENTANAS FLOTANTES (Sintaxis Estricta por Bloques) ──

# Reglas para Dolphin
windowrule = float 1, match:class ^(org\.kde\.dolphin)$
windowrule = size 1000 700, match:class ^(org\.kde\.dolphin)$
windowrule = center 1, match:class ^(org\.kde\.dolphin)$

# Reglas para Telegram
windowrule = float 1, match:class ^(org\.telegram\.desktop)$
windowrule = size 900 700, match:class ^(org\.telegram\.desktop)$
windowrule = center 1, match:class ^(org\.telegram\.desktop)$

# Reglas para WhatsApp
windowrule = float 1, match:class ^(whatsapp-for-linux)$
windowrule = size 1000 750, match:class ^(whatsapp-for-linux)$
windowrule = center 1, match:class ^(whatsapp-for-linux)$

# THUNAR
bind = SUPER, E, exec, thunar

# Directiva BLUETHOOT
exec-once = blueman-applet

# Directiva AUDIO volumeicon
exec-once = volumeicon

# Directiva BRILLO de pantalla
exec-once = brightnessctl


# Atajos para controlar el Brillo de pantalla (Subir / Bajarn en pasos de 5%)
binde = , XF86MonBrightnessUp, exec, brightnessctl set +5%
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Atajos para controlar el Volumen (Subir / Bajar / Mutear)
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# DESARROLLO
# Iniciar llavero Keyring
exec-once = gnome-keyring-daemon --start --components=secrets
