# Change the default Omarchy look'n'feel

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Change to niri-like side-scrolling layout
    # layout = scrolling

    snap {
    	enabled = true              # Activa el pegado magnético para ventanas flotantes
        window_gap = 10             # Distancia mínima en píxeles entre ventanas antes de pegarse
        monitor_gap = 10            # Distancia mínima en píxeles entre la ventana y los bordes de la pantalla
        border_overlap = false      # Si es true, se pegan encimando sus bordes para no duplicar espacio
        respect_gaps = false        # Si es true, el pegado respetará los gaps_in definidos en general
    }
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    # Use round window corners
    rounding =6
	rounding_power = 6.0
	active_opacity = 0.97
	inactive_opacity = 0.80
	fullscreen_opacity = 1.0
	dim_modal = true
	dim_inactive = false
	dim_strength = 0.8
	dim_special = 5.2
	dim_around = 0.4
	border_part_of_window = true

	blur {
		enabled = true
	    size = 1
	    passes = 1                  # Recomendado: más capas (passes) mejoran la calidad del difuminado
	    new_optimizations = true     # Optimización nativa para que no consuma recursos de más
	    xray = true                # Si es true, ignora otras ventanas flotantes debajo para ahorrar GPU
	    vibrancy = 0.901
	    vibrancy_darkness = 1.5
	    brightness = 0.4
	    contrast = 1.5
	}

	shadow {
		enabled = true              # Activa las sombras en las ventanas
	    range = 4                   # Tamaño/rango de la sombra en pixeles
	    render_power = 3            # Fuerza de desvanecimiento [1 - 4] (a más poder, caída más rápida)
	    sharp = false               # Si es true, la sombra será rígida/sólida (estilo retro)
	    color = 0xee1a1a1a          # Color de sombra activa (el Alpha define la opacidad inicial)
	    # color_inactive = unset    # Color de sombra inactiva (si no se pone, usa el color por defecto)
	    offset = 0 0                # Desplazamiento de la sombra en ejes X e Y (ej. 0 0 está centrada)
	    scale = 1.0                 # Escala de la sombra [0.0 - 1.0]
	}

	glow {
		enabled = true              # Activa el resplandor interno en las ventanas
	    range = 10                  # Tamaño/rango del resplandor en pixeles
	    render_power = 3            # Fuerza de desvanecimiento [1 - 4] (más alto = desvanecimiento más rápido)
	    color = 0xee1a1a1a          # Color del resplandor activo (puedes cambiarlo por un tono neón)
	    # color_inactive = unset    # Color del resplandor inactivo (si no se pone, usa el color por defecto)
	}
		
    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}


# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    # Disable all animations
	enabled = true
	workspace_wraparound = false
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
    single_window_aspect_ratio = 1 1
    single_window_aspect_ratio_tolerance = 0.1
}

# https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
scrolling {
    # See only one column per screen instead of two
    column_width = 1.0
}
